cstoreconsole/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from cstoreapp import views, apis

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.home, name='home'),

                  # CStore URL
                  path('cstore/sign_in/', auth_views.login,
                       {'template_name': 'cstore/sign_in.html'},
                       name='cstore-sign-in'),
                  path('cstore/sign_out/', auth_views.logout,
                       {'next_page': '/'},
                       name='cstore-sign-out'),
                  path('cstore/sign_up/', views.cstore_sign_up,
                       name='cstore-sign-up'),

                  path('cstore/account/', views.cstore_account, name='cstore-account'),
                  path('cstore/product/', views.cstore_product, name='cstore-product'),
                  path('cstore/product/add', views.cstore_add_product, name='cstore-add-product'),
                  path('cstore/product/edit/<int:product_id>/', views.cstore_edit_product, name='cstore-edit-product'),
                  path('cstore/order/', views.cstore_order, name='cstore-order'),
                  path('cstore/report/', views.cstore_report, name='cstore-report'),
                  path('cstore/reward/', views.cstore_reward, name='cstore-reward'),
                  path('cstore/', views.cstore_home, name='cstore-home'),

                  # Sign IN/ Sign Up/ Sign Out
                  path('api/social/', include('rest_framework_social_oauth2.urls')),

                  # API for customers
                  path('api/customer/cstores/', apis.customer_get_cstores),
                  path('api/customer/products/<int:cstore_id>/', apis.customer_get_products),
                  path('api/customer/order/add/', apis.customer_add_order),
                  path('api/customer/order/latest/', apis.customer_get_latest_order),
                  path('api/cstore/order/notification/<str:last_request_time>/', apis.cstore_order_notification),

                  path('api/cstore/order/notification/<slug:last_request_time>/', apis.cstore_order_notification),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""Developed by Abhijeeth
Copyrights @abhijeethbaregal@2018"""

cstoreapp/models.py
"""Developed by Abhijeeth
Copyrights @abhijeethbaregal@2018"""


from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Cstore(models.Model):
    # cstore belong to one owner ad ne owner has one cstore
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='cstore')
    name = models.CharField(max_length=500)
    phone = models.CharField(max_length=500)
    address = models.CharField(max_length=500)
    logo = models.ImageField(upload_to='cstore_logo/', blank=False)

    def __str__(self):
        return self.name


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
    avatar = models.CharField(max_length=500)
    phone = models.CharField(max_length=500, blank=True)
    address = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.user.get_full_name()


class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='driver')
    avatar = models.CharField(max_length=500)
    phone = models.CharField(max_length=500, blank=True)
    address = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.user.get_full_name()


class Product(models.Model):
    cstore = models.ForeignKey(Cstore, on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    short_description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='product_images/', blank=False)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Order(models.Model):
    COOKING = 1
    READY = 2
    ONTHEWAY = 3
    DELIVERED = 4

    STATUS_CHOICES = (
        (COOKING, "Preparing"),
        (READY, "Ready"),
        (ONTHEWAY, "On the way"),
        (DELIVERED, "Delivered")
    )

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    cstore = models.ForeignKey(Cstore, on_delete=models.CASCADE)

    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, blank=True, null=True)

    address = models.CharField(max_length=500)
    total = models.IntegerField()
    status = models.IntegerField(choices=STATUS_CHOICES)
    created_at = models.DateTimeField(default=timezone.now)
    picked_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return str(self.id)


class OrderDetails(models.Model):
    order = models.ForeignKey(Order, related_name='order_details', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    sub_total = models.IntegerField()

    def __str__(self):
        return str(self.id)

cstoreapp/forms.py
"""Developed by Abhijeeth
Copyrights @abhijeethbaregal@2018"""

from django import forms

from django.contrib.auth.models import User

from cstoreapp.models import Cstore, Product


class UserForm(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "password", "first_name", "last_name", "email")


class UserFormForEdit(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")


class CstoreForm(forms.ModelForm):
    class Meta:
        model = Cstore
        fields = ("name", "phone", "address", "logo")


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('cstore',)

cstoreapp/views.py
"""Developed by Abhijeeth
Copyrights @abhijeethbaregal@2018"""


from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from cstoreapp.forms import UserForm, CstoreForm, UserFormForEdit, ProductForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from cstoreapp.models import Product, Order


# Create your views here.

def home(request):
    return redirect(cstore_home)


@login_required(login_url='/cstore/sign_in')
def cstore_home(request):
    return redirect(cstore_order)


@login_required(login_url='/cstore/sign_in')
def cstore_account(request):
    user_form = UserFormForEdit(instance=request.user)
    cstore_form = CstoreForm(instance=request.user.cstore)

    if request.method == "POST":
        user_form = UserFormForEdit(request.POST, instance=request.user)
        cstore_form = CstoreForm(request.POST, request.FILES, instance=request.user.cstore)

        if user_form.is_valid() and cstore_form.is_valid():
            user_form.save()
            cstore_form.save()
    return render(request, 'cstore/account.html', {
        "user_form": user_form,
        "cstore_form": cstore_form
    })


@login_required(login_url='/cstore/sign_in')
def cstore_product(request):
    products = Product.objects.filter(cstore=request.user.cstore).order_by("-id")
    return render(request, 'cstore/product.html', {"products": products})


@login_required(login_url='/cstore/sign_in')
def cstore_order(request):
    if request.method == "POST":
        order = Order.objects.get(id=request.POST["id"], cstore=request.user.cstore)
        if order.status == Order.COOKING:
            order.status = Order.READY
            order.save()
    orders = Order.objects.filter(cstore=request.user.cstore).order_by("-id")
    return render(request, 'cstore/order.html', {"orders": orders})


@login_required(login_url='/cstore/sign_in')
def cstore_report(request):
    return render(request, 'cstore/report.html', {})


@login_required(login_url='/cstore/sign_in')
def cstore_reward(request):
    return render(request, 'cstore/reward.html', {})


def cstore_sign_up(request):
    user_form = UserForm()
    cstore_form = CstoreForm()

    if request.method == "POST":
        user_form = UserForm(request.POST)
        cstore_form = CstoreForm(request.POST, request.FILES)

        if user_form.is_valid() and cstore_form.is_valid():
            new_user = User.objects.create_user(**user_form.cleaned_data)
            new_cstore = cstore_form.save(commit=False)
            new_cstore.user = new_user
            # saving to database
            new_cstore.save()

            login(request, authenticate(
                username=user_form.cleaned_data["username"],
                password=user_form.cleaned_data["password"]
            ))
            return redirect(cstore_product)

    return render(request, 'cstore/sign_up.html', {
        "user_form": user_form,
        "cstore_form": cstore_form
    })


@login_required(login_url='/cstore/sign_in')
def cstore_add_product(request):
    form = ProductForm()

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.cstore = request.user.cstore
            product.save()
            return redirect(cstore_product)

    return render(request, 'cstore/add_product.html', {
        "form": form
    })


@login_required(login_url='/cstore/sign_in')
def cstore_edit_product(request, product_id):
    form = ProductForm(instance=Product.objects.get(id=product_id))

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=Product.objects.get(id=product_id))
        if form.is_valid():
            form.save()
            return redirect(cstore_product)

    return render(request, 'cstore/edit_product.html', {
        "form": form
    })

cstoreapp/templates/cstore/account.html
{% extends 'cstore/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class="col-lg-offset-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Account
                </h4>
            </div>
            <div class="panel-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form user_form %}
                    {% bootstrap_form cstore_form %}
                    <button type="submit" class="btn btn-pink">Update</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{#"""Developed by Abhijeeth#}
{#Copyrights @abhijeethbaregal@2018"""#}

cstoreapp/templates/cstore/add_product.html
{% extends 'cstore/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class = "col-lg-offset-2 col-lg-8">
        <div class ="panel">
            <div class="panel-heading bg-blue">
                <h4 class = "panel-title text-center text-white">
                    Add Product
                </h4>
            </div>
            <div class = "panel-body">
                <form method = "POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {%  bootstrap_form form %}
                    <button type="submit" class="btn btn-pink" >Create</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{#"""Developed by Abhijeeth#}
{#Copyrights @abhijeethbaregal@2018"""#}

cstoreapp/templates/cstore/base.html
{% extends 'base.html' %}

{% block title %} Cstore {% endblock %}

{% block script %}
    <script>
        $(document).ready(function() {
            var now = new Date();
            setInterval(function() {
                $.ajax({
                    url: '/api/cstore/order/notification/' + now.toISOString() + '/',
                    method: 'GET',
                    success: function(data) {
                        if (data['notification'] === 0) {
                            $('.badge').text('');
                        } else {
                            $('.badge').text(data['notification']);
                        }
                    }
                })
            }, 3000)
        })

    </script>
{% endblock %}

{% block sidebar %}

    {% url 'cstore-order' as cstore_order_url %}
    {% url 'cstore-product' as cstore_product_url %}
    {% url 'cstore-report' as cstore_report_url %}
    {% url 'cstore-account' as cstore_account_url %}
    {% url 'cstore-reward' as cstore_reward_url %}

    <div class="text-center">
      <img class="img-circle" src="{{ MEDIA_URL }}{{ request.user.cstore.logo }}"
          width="70" height="70" />
      <br/>
      <br/>
      <h4>Hi, {{ request.user.get_full_name }}</h4>
      <h5>{{ request.user.cstore.name }}</h5>
    </div>

    <div class="list-group">
      <span class="text-uppercase">Dashboard</span>

      <a href="{% url 'cstore-order' %}"
          class="list-group-item {% if request.path == cstore_order_url %} active {% endif %} ">
          Orders
          <span class="badge"></span>
      </a>
      <a href="{% url 'cstore-product' %}"
          class="list-group-item {% if request.path == cstore_product_url %} active {% endif %} ">Product</a>
      <a href="{% url 'cstore-report' %}"
          class="list-group-item {% if request.path == cstore_report_url %} active {% endif %} ">Reports</a>

      <span class="text-uppercase">Profile</span>
      <a href="{% url 'cstore-account' %}"
          class="list-group-item {% if request.path == cstore_account_url %} active {% endif %} ">Account</a>
    </div>

    <div class="text-center">
      <a href="{% url 'cstore-sign-out' %}?next={{ request.path }}"
          class="btn btn-pink">Logout</a>
    </div>

{% endblock %}


{#"""Developed by Abhijeeth#}
{#Copyrights @abhijeethbaregal@2018"""#}

cstoreapp/templates/cstore/edit_product.html
{% extends 'cstore/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class = "col-lg-offset-2 col-lg-8">
        <div class ="panel">
             <div class="panel-heading bg-blue">
                <h4 class = "panel-title text-center text-white">
                    Edit Product
                </h4>
             </div>
            <div class = "panel-body">
                <form method = "POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {%  bootstrap_form form %}
                    <button type="submit" class="btn btn-pink" >Update</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{#"""Developed by Abhijeeth#}
{#Copyrights @abhijeethbaregal@2018"""#}

cstoreapp/templates/cstore/order.html
{% extends 'cstore/base.html' %}

{% block page %}

    <div class="panel">
        <div class="panel-heading bg-blue">
            <h4 class="panel-title text-center text-white">Orders</h4>
        </div>
        <div class="panel-body">
            <br/>
            <table class="table table-bordered table-hover table-striped">
                <thead>
                  <tr class="bg-gray text-white">
                    <th>Id</th>
                    <th>Order Details</th>
                    <th>Customer</th>
                    <th>Driver</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                        <tr>
                            <td scope="row">{{ order.id }}</td>
                            <td>
                              {% for od in order.order_details.all %}
                                  {{ od.product.name }} {{ od.product.price }}
                                  x {{ od.quantity }} = ${{ od.sub_total }}
                              {% endfor %}
                            </td>
                            <td>{{ order.customer }}</td>
                            <td>{{ order.driver }}</td>
                            <td>{{ order.total }}</td>
                            <td>{{ order.get_status_display }}</td>
                            <td>
                                {% if order.status == 1 %}
                                    <form method="POST">
                                      {% csrf_token %}
                                      <input name="id" value="{{ order.id }}" hidden title="id">
                                      <button class="btn btn-success">Ready</button>
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

{#"""Developed by Abhijeeth#}
{#Copyrights @abhijeethbaregal@2018"""#}

cstoreapp/templates/cstore/product.html
{% extends 'cstore/base.html' %}

{% block page %}

    <div class="panel">
        <div class="panel-heading bg-blue">
            <h4 class="panel-title text-center text-white">products</h4>
        </div>
        <div class="panel-body">
            <div class="text-right">
                <a href="{% url 'cstore-add-product' %}" class="btn btn-pink">Add product</a>
                <br/>
                <br/>
            </div>

            <table class="table table-bordered table-hover table-striped">
                <thead>
                  <tr class="bg-gray text-white">
                    <th>Id</th>
                    <th>Name</th>
                    <th>Short Description</th>
                    <th>Price</th>
                    <th class="text-center">Image</th>
                  </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                        <tr>
                          <td scope="row">{{ product.id }}</td>
                          <td><a href="{% url 'cstore-edit-product' product.id %}">{{ product.name }}</a></td>
                          <td>{{ product.short_description }}</td>
                          <td>{{ product.price }}</td>
                          <td class="text-center"><img class="img-rounded"
                              src="{{ MEDIA_URL }}{{ product.image }}" width="50" height="50"></td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>



{% endblock %}


{#"""Developed by Abhijeeth#}
{#Copyrights @abhijeethbaregal@2018"""#}

cstoreapp/templates/cstore/report.html
{% extends 'cstore/base.html' %}

{% block page %}

    report

{% endblock %}

{#"""Developed by Abhijeeth#}
{#Copyrights @abhijeethbaregal@2018"""#}

cstoreapp/templates/cstore/reward.html
{% extends 'cstore/base.html' %}

{% block page %}

    reward

{% endblock %}

{#"""Developed by Abhijeeth#}
{#Copyrights @abhijeethbaregal@2018"""#}

cstoreapp/templates/cstore/sign_in.html
{% extends 'base_signup.html' %}
{% load bootstrap3 %}

{% block title %}Sign In{%  endblock %}
{% block heading %}Cstore- Sign-In{% endblock %}

{%  block content %}
 <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
        <button type="submit" class="btn btn-pink pull-right">Sign In</button>
    </form>
    <a href="{% url 'cstore-sign-up' %}">Become a Cstore</a>
{% endblock %}

{#"""Developed by Abhijeeth#}
{#Copyrights @abhijeethbaregal@2018"""#}

cstoreapp/templates/cstore/sign_up.html
{% extends 'base_signup.html' %}
{%  load bootstrap3 %}
{% block title %}Sign In{%  endblock %}
{% block heading %}Cstore- Sign-In{% endblock %}

{%  block content %}
  <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form user_form %}
        {% bootstrap_form cstore_form %}
  <button type = "submit" class="btn btn-pink pull-right">Sign Up</button>
  </form>
    <a href=""{% url "cstore-sign-in" %}>Already have an account</a>

{% endblock %}

{#"""Developed by Abhijeeth#}
{#Copyrights @abhijeethbaregal@2018"""#}